# permissions for end users to view pulprestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulprestore-viewer-role
rules:
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulprestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulprestores/status
  verbs:
  - get
