# permissions for end users to edit pulpbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulpbackup-editor-role
rules:
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulpbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulpbackups/status
  verbs:
  - get
