## Append samples you want in your CSV to this file as resources ##
resources:
- repo-manager_v1alpha1_pulp.yaml
- simple.yaml
- galaxy.yaml
- repo-manager_v1alpha1_pulpbackup.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
