apiVersion: repo-manager.pulpproject.org/v1alpha1
kind: PulpBackup
metadata:
  name: pulpbackup-sample
spec:
  deployment_type: pulp
  backup_storage_class: standard
  pulp_instance_name: pulp
  admin_password_secret: example-pulp-admin-password
