apiVersion: repo-manager.pulpproject.org/v1alpha1
kind: Pulp
metadata:
  name: pulp
spec:
  deployment_type: pulp
  is_k8s: true
  image_version: latest
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: test
#            operator: In
#            values:
#            - test
  api:
    replicas: 1
  database:
    replicas: 1
    type: postgres
  content:
    replicas: 1
  worker:
    replicas: 1
  web:
    replicas: 1

  pulp_settings:
    api_root: "/pulp/"
